[package]
name = "api_req_derive"
version = "0.2.0"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/api_req_derive"
description = "Derive macro for api_req"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
regex = { version = "1.11.1" }

[dev-dependencies]
api_req = { path = "../api_req", version = "0.2.0" }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.15", features = [] }
serde_urlencoded = { version = "0.7.0" }
