[package]
name = "api_req_derive"
version = "0.5.1"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/api_req_derive"
description = "Derive macro for api_req"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
regex = { version = "1.12" }

[dev-dependencies]
api_req = { path = "../api_req", version = "0.5" }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = [] }
serde_urlencoded = { version = "0.7" }

[features]
default = []
cookies = []
