[package]
name = "api_req"
version = "0.5.1"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/api_req"
description = "A library for making API requests with ease"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
api_req_derive = { path = "../api_req_derive", version = "0.5" }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
serde_urlencoded = { version = "0.7" }
pin-project = "1.1"
futures-util = { version = "0.3", optional = true }
bytes = { version = "1.10", optional = true }

[features]
default = []
stream = ["dep:futures-util", "dep:bytes", "reqwest/stream"]
cookies = ["reqwest/cookies", "api_req_derive/cookies"]
