[package]
name = "api_req"
version = "0.2.3"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/api_req"
description = "A library for making API requests with ease"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
api_req_derive = { path = "../api_req_derive", version = "0.2.2" }
dotenv = "0.15.0"
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
serde_json = { version = "1.0" }
serde_urlencoded = { version = "0.7.0" }
pin-project = "1.1.10"
futures-util = { version = "0.3.31", optional = true }
bytes = { version = "1.10.1", optional = true }

[features]
default = []
stream = ["dep:futures-util", "dep:bytes", "reqwest/stream"]
